package com.alpriest.energystats.ui.settings

enum class SettingsScreen {
    Settings,
    Debug,
    Battery,
    BatterySOC,
    BatteryChargeTimes,
    Inverter,
    PopupInverterSchedule,
    InverterSchedule,
    Dataloggers,
    SelfSufficiencyEstimates,
    FinancialModel,
    SolarBandings,
    SolcastSolarPrediction,
    FAQ,
    EditSchedule,
    EditPhase,
    TemplateList,
    EditTemplate,
    APIKey,
    PowerStation,
    DataSettings,
    BatteryVersions,
    ConfigureExportLimit,
    ConfigureMaxSoc,
    ConfigurePeakShaving,
    FactoryResetAppSettings,
    ConfigureWorkMode
}